# Generated by Django 3.0.4 on 2020-03-05 23:19

import datetime
from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='EmployeeOrder',
        ),
        migrations.DeleteModel(
            name='EmployerOrder',
        ),
        migrations.AddField(
            model_name='employee',
            name='searchfor',
            field=models.ManyToManyField(to='main_app.Job'),
        ),
        migrations.AddField(
            model_name='employee',
            name='skils',
            field=models.ManyToManyField(to='main_app.Skil'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employer',
            name='searchfor',
            field=models.ManyToManyField(to='main_app.Job'),
        ),
        migrations.AddField(
            model_name='employer',
            name='user',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='group',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='main_app.JobGroup'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'تمام وقت'), (2, 'پاره وقت'), (3, 'پروژه\u200cای'), (4, 'کارآموزی'), (5, 'توافقی'), (6, 'سایر')], default=datetime.datetime(2020, 3, 5, 23, 19, 10, 665909, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=1, srid=4326),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='title',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobgroup',
            name='title',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skil',
            name='description',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skil',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='joborder',
            name='searchfor',
            field=models.ManyToManyField(to='main_app.Job'),
        ),
        migrations.AddField(
            model_name='joborder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
