# Generated by Django 3.0.4 on 2020-03-07 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200307_1944'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
    ]
