# Generated by Django 3.0.4 on 2020-03-07 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_joborder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skil',
        ),
    ]
